# Form implementation generated from reading ui file 'loginpage.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(534, 762)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(-10, 0, 591, 761))
        self.label.setStyleSheet("border-image: url(:/bg/icon/bg.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/bg.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(90, 220, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(80, 310, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(30, 410, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.login = QtWidgets.QPushButton(parent=Form)
        self.login.setGeometry(QtCore.QRect(120, 510, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.login.setFont(font)
        self.login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.login.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(63, 63, 63);\n"
"    color: white;\n"
"    padding: 10px 24px;\n"
"    text-align: center;\n"
"    font-size: 25px;\n"
"    margin: 4px 2px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(53, 53, 53);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(121, 121, 121);\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon.fromTheme("lock")
        self.login.setIcon(icon)
        self.login.setObjectName("login")
        self.pid_entry = QtWidgets.QLineEdit(parent=Form)
        self.pid_entry.setGeometry(QtCore.QRect(180, 220, 291, 41))
        self.pid_entry.setStyleSheet("\n"
"font: 25 14pt \"Calibri\";\n"
"color: rgb(0, 9, 9);\n"
"background-color: rgb(243, 243, 243);\n"
"border-radius:10px;")
        self.pid_entry.setText("")
        self.pid_entry.setObjectName("pid_entry")
        self.label_15 = QtWidgets.QLabel(parent=Form)
        self.label_15.setGeometry(QtCore.QRect(170, 70, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.email_entry = QtWidgets.QLineEdit(parent=Form)
        self.email_entry.setGeometry(QtCore.QRect(180, 310, 291, 41))
        self.email_entry.setStyleSheet("\n"
"font: 25 14pt \"Calibri\";\n"
"color: rgb(0, 9, 9);\n"
"background-color: rgb(243, 243, 243);\n"
"border-radius:10px;")
        self.email_entry.setText("")
        self.email_entry.setObjectName("email_entry")
        self.password_entry = QtWidgets.QLineEdit(parent=Form)
        self.password_entry.setGeometry(QtCore.QRect(180, 410, 291, 41))
        self.password_entry.setStyleSheet("\n"
"font: 25 14pt \"Calibri\";\n"
"color: rgb(0, 9, 9);\n"
"background-color: rgb(243, 243, 243);\n"
"border-radius:10px;")
        self.password_entry.setText("")
        self.password_entry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_entry.setObjectName("password_entry")
        self.new_sign_in = QtWidgets.QPushButton(parent=Form)
        self.new_sign_in.setGeometry(QtCore.QRect(130, 570, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.new_sign_in.setFont(font)
        self.new_sign_in.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.new_sign_in.setStyleSheet("\n"
"QPushButton {\n"
"                background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(44, 49, 149, 255),  stop:0.5 rgba(57, 64, 159, 255), stop:1 rgba(96, 56, 161, 255));\n"
"                border: none;\n"
"                color: white;\n"
"                padding: 10px 24px;\n"
"                text-align: center;\n"
"                text-decoration: none;\n"
"                display: inline-block;\n"
"                font-size: 12px;\n"
"                margin: 4px 2px;\n"
"                cursor: pointer;\n"
"                border-radius: 12px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                color: rgb(214, 61, 92);\n"
"    \n"
"            }\n"
"\n"
"            QPushButton:pressed {\n"
"                background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(42, 34, 137, 205),  stop:0.5 rgba(61, 64, 159, 205), stop:1 rgba(113, 16, 131, 205));\n"
"            }\n"
"\n"
"\n"
"")
        self.new_sign_in.setObjectName("new_sign_in")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 121, 121))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icon/Edu_logo-removebg-preview.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.email_error_message = QtWidgets.QLabel(parent=Form)
        self.email_error_message.setGeometry(QtCore.QRect(100, 360, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.email_error_message.setFont(font)
        self.email_error_message.setStyleSheet("color: rgb(255, 0, 0);")
        self.email_error_message.setText("")
        self.email_error_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.email_error_message.setObjectName("email_error_message")
        self.pid_error_message = QtWidgets.QLabel(parent=Form)
        self.pid_error_message.setGeometry(QtCore.QRect(60, 260, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pid_error_message.setFont(font)
        self.pid_error_message.setStyleSheet("color: rgb(255, 0, 0);")
        self.pid_error_message.setText("")
        self.pid_error_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pid_error_message.setObjectName("pid_error_message")
        self.password_error_message = QtWidgets.QLabel(parent=Form)
        self.password_error_message.setGeometry(QtCore.QRect(40, 460, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password_error_message.setFont(font)
        self.password_error_message.setStyleSheet("color: rgb(255, 0, 0);")
        self.password_error_message.setText("")
        self.password_error_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password_error_message.setObjectName("password_error_message")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "PID:"))
        self.label_5.setText(_translate("Form", "Email:"))
        self.label_6.setText(_translate("Form", "Password:"))
        self.login.setText(_translate("Form", "LOGIN"))
        self.pid_entry.setPlaceholderText(_translate("Form", "Enter your PID Number"))
        self.label_15.setText(_translate("Form", "EDU-HUB"))
        self.email_entry.setPlaceholderText(_translate("Form", "Enter your college email id"))
        self.password_entry.setPlaceholderText(_translate("Form", "  Password"))
        self.new_sign_in.setText(_translate("Form", "New to Eduhub ? Please Sign in"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
