# Form implementation generated from reading ui file 'signuppage.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(534, 762)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 601, 761))
        self.label.setStyleSheet("border-image: url(:/bg/icon/universe.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/bg.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(60, 190, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.pid_entry_2 = QtWidgets.QLineEdit(parent=Form)
        self.pid_entry_2.setGeometry(QtCore.QRect(170, 180, 311, 41))
        self.pid_entry_2.setStyleSheet("\n"
"font: 25 14pt \"Calibri\";\n"
"color: rgb(0, 9, 9);\n"
"background-color: rgb(243, 243, 243);\n"
"border-radius:10px;")
        self.pid_entry_2.setText("")
        self.pid_entry_2.setObjectName("pid_entry_2")
        self.email_entry_2 = QtWidgets.QLineEdit(parent=Form)
        self.email_entry_2.setGeometry(QtCore.QRect(170, 270, 311, 41))
        self.email_entry_2.setStyleSheet("\n"
"font: 25 14pt \"Calibri\";\n"
"color: rgb(0, 9, 9);\n"
"background-color: rgb(243, 243, 243);\n"
"border-radius:10px;")
        self.email_entry_2.setText("")
        self.email_entry_2.setObjectName("email_entry_2")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(50, 270, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=Form)
        self.label_11.setGeometry(QtCore.QRect(30, 500, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.password_entry_2 = QtWidgets.QLineEdit(parent=Form)
        self.password_entry_2.setGeometry(QtCore.QRect(170, 500, 311, 41))
        self.password_entry_2.setStyleSheet("\n"
"font: 25 14pt \"Calibri\";\n"
"color: rgb(0, 9, 9);\n"
"background-color: rgb(243, 243, 243);\n"
"border-radius:10px;")
        self.password_entry_2.setText("")
        self.password_entry_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_entry_2.setObjectName("password_entry_2")
        self.confirm_password_entry_2 = QtWidgets.QLineEdit(parent=Form)
        self.confirm_password_entry_2.setGeometry(QtCore.QRect(170, 550, 311, 41))
        self.confirm_password_entry_2.setStyleSheet("\n"
"font: 25 14pt \"Calibri\";\n"
"color: rgb(0, 9, 9);\n"
"background-color: rgb(243, 243, 243);\n"
"border-radius:10px;")
        self.confirm_password_entry_2.setText("")
        self.confirm_password_entry_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirm_password_entry_2.setObjectName("confirm_password_entry_2")
        self.gender_entry_2 = QtWidgets.QComboBox(parent=Form)
        self.gender_entry_2.setGeometry(QtCore.QRect(160, 440, 111, 31))
        self.gender_entry_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius:5px;")
        self.gender_entry_2.setObjectName("gender_entry_2")
        self.gender_entry_2.addItem("")
        self.gender_entry_2.addItem("")
        self.label_12 = QtWidgets.QLabel(parent=Form)
        self.label_12.setGeometry(QtCore.QRect(40, 440, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=Form)
        self.label_13.setGeometry(QtCore.QRect(290, 440, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.branch_entry_2 = QtWidgets.QComboBox(parent=Form)
        self.branch_entry_2.setGeometry(QtCore.QRect(390, 440, 101, 31))
        self.branch_entry_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius:5px;")
        self.branch_entry_2.setObjectName("branch_entry_2")
        self.branch_entry_2.addItem("")
        self.branch_entry_2.addItem("")
        self.branch_entry_2.addItem("")
        self.branch_entry_2.addItem("")
        self.label_14 = QtWidgets.QLabel(parent=Form)
        self.label_14.setGeometry(QtCore.QRect(50, 350, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.name_entry_2 = QtWidgets.QLineEdit(parent=Form)
        self.name_entry_2.setGeometry(QtCore.QRect(170, 350, 311, 41))
        self.name_entry_2.setStyleSheet("\n"
"font: 25 14pt \"Calibri\";\n"
"color: rgb(0, 9, 9);\n"
"background-color: rgb(243, 243, 243);\n"
"border-radius:10px;")
        self.name_entry_2.setText("")
        self.name_entry_2.setObjectName("name_entry_2")
        self.signup_button = QtWidgets.QPushButton(parent=Form)
        self.signup_button.setGeometry(QtCore.QRect(150, 630, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.signup_button.setFont(font)
        self.signup_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.signup_button.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(63, 63, 63);\n"
"    color: white;\n"
"    padding: 10px 24px;\n"
"    text-align: center;\n"
"    font-size: 25px;\n"
"    margin: 4px 2px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(53, 53, 53);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(121, 121, 121);\n"
"}\n"
"\n"
"\n"
"")
        self.signup_button.setObjectName("signup_button")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(50, 30, 121, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icon/Edu_logo-removebg-preview.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.password_error_message_2 = QtWidgets.QLabel(parent=Form)
        self.password_error_message_2.setGeometry(QtCore.QRect(50, 600, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password_error_message_2.setFont(font)
        self.password_error_message_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.password_error_message_2.setText("")
        self.password_error_message_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password_error_message_2.setObjectName("password_error_message_2")
        self.email_error_message_2 = QtWidgets.QLabel(parent=Form)
        self.email_error_message_2.setGeometry(QtCore.QRect(110, 310, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.email_error_message_2.setFont(font)
        self.email_error_message_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.email_error_message_2.setText("")
        self.email_error_message_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.email_error_message_2.setObjectName("email_error_message_2")
        self.pid_error_message_2 = QtWidgets.QLabel(parent=Form)
        self.pid_error_message_2.setGeometry(QtCore.QRect(70, 230, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pid_error_message_2.setFont(font)
        self.pid_error_message_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.pid_error_message_2.setText("")
        self.pid_error_message_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pid_error_message_2.setObjectName("pid_error_message_2")
        self.name_error_message_2 = QtWidgets.QLabel(parent=Form)
        self.name_error_message_2.setGeometry(QtCore.QRect(110, 400, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.name_error_message_2.setFont(font)
        self.name_error_message_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.name_error_message_2.setText("")
        self.name_error_message_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_error_message_2.setObjectName("name_error_message_2")
        self.label_16 = QtWidgets.QLabel(parent=Form)
        self.label_16.setGeometry(QtCore.QRect(180, 60, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "PID:"))
        self.pid_entry_2.setPlaceholderText(_translate("Form", "Enter your PID Number"))
        self.email_entry_2.setPlaceholderText(_translate("Form", "Enter your college email id"))
        self.label_10.setText(_translate("Form", "Email:"))
        self.label_11.setText(_translate("Form", "Password:"))
        self.password_entry_2.setPlaceholderText(_translate("Form", "Set a Password"))
        self.confirm_password_entry_2.setPlaceholderText(_translate("Form", "Confirm Password"))
        self.gender_entry_2.setItemText(0, _translate("Form", "Male"))
        self.gender_entry_2.setItemText(1, _translate("Form", "Female"))
        self.label_12.setText(_translate("Form", "Gender:"))
        self.label_13.setText(_translate("Form", "Branch:"))
        self.branch_entry_2.setItemText(0, _translate("Form", "INFT"))
        self.branch_entry_2.setItemText(1, _translate("Form", "COMS"))
        self.branch_entry_2.setItemText(2, _translate("Form", "MECH"))
        self.branch_entry_2.setItemText(3, _translate("Form", "EXTC"))
        self.label_14.setText(_translate("Form", "Name:"))
        self.name_entry_2.setPlaceholderText(_translate("Form", "Enter your First and Last name"))
        self.signup_button.setText(_translate("Form", "SIGN UP"))
        self.label_16.setText(_translate("Form", "EDU-HUB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
